# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ "amdgpu" ]; # KASTEN: Added amdgpu, but didn't help steam start
  boot.kernelModules = [
    "kvm-amd"
    "btusb"
    "bluetooth"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/29c5f8aa-de53-4041-9c04-a03e7ab8cb2f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E513-2F9F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/fa3b0757-873d-49ff-befa-f5734251a79c"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp16s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp17s0u4u1u3.useDHCP = lib.mkDefault true;
  networking.interfaces.enp16s0.wakeOnLan.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #
  # Bluetooth
  #
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  hardware.enableAllFirmware = true;

  # KASTEN: Gets steam to launch, but vkcube --validate still has errors with vulkan
  # hardware.opengl -> hardware.graphics
  hardware.graphics = {
    enable = true;
    # driSupport = true; #NO longer has any effect
    enable32Bit = true;
    extraPackages = with pkgs; [
      mesa

      # KASTEN: Didn't help fix this error:
      #   terminator_CreateInstance: Received return code -3 from call to vkCreateInstance in ICD /nix/store/js9cfbjvlsls14nddk39fw74vyvlhz4l-mesa-25.0.7/lib/libvulkan_dzn.so
      vulkan-loader
      vulkan-validation-layers
      vulkan-extension-layer
    ];
  };

}
